title: Alexandre Gaillard
logo: /assets/img/logo.png
description: PhD Student, Toulouse School of Economics
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
plugins:
  - jekyll-redirect-from
